### Importing necessary libraries 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier

In [2]:
import os
os.chdir('C:\\Users\\WELCOME\\Downloads\\HACK Analytics vidhya\\lon prediction')

### Reading training data

In [3]:
df_train = pd.read_csv('train_ctrUa4K.csv')

In [4]:
df_train.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [5]:
df_train.drop(['Loan_ID'], axis = 1, inplace = True )

In [6]:
df_train.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [7]:
df_train.shape

(614, 12)

In [8]:
df_train['Dependents'].value_counts()

0     345
1     102
2     101
3+     51
Name: Dependents, dtype: int64

In [9]:
df_train['Dependents'].replace('3+', 3, inplace=True)

In [10]:
df_train['Dependents'].value_counts()

0    345
1    102
2    101
3     51
Name: Dependents, dtype: int64

In [11]:
df_train['Loan_Status'].value_counts()

Y    422
N    192
Name: Loan_Status, dtype: int64

In [12]:
df_train.describe().T

count         mean          std    min     25%     50%  \
ApplicantIncome    614.0  5403.459283  6109.041673  150.0  2877.5  3812.5   
CoapplicantIncome  614.0  1621.245798  2926.248369    0.0     0.0  1188.5   
LoanAmount         592.0   146.412162    85.587325    9.0   100.0   128.0   
Loan_Amount_Term   600.0   342.000000    65.120410   12.0   360.0   360.0   
Credit_History     564.0     0.842199     0.364878    0.0     1.0     1.0   

                       75%      max  
ApplicantIncome    5795.00  81000.0  
CoapplicantIncome  2297.25  41667.0  
LoanAmount          168.00    700.0  
Loan_Amount_Term    360.00    480.0  
Credit_History        1.00      1.0

In [13]:
df_train.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [14]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             601 non-null    object 
 1   Married            611 non-null    object 
 2   Dependents         599 non-null    object 
 3   Education          614 non-null    object 
 4   Self_Employed      582 non-null    object 
 5   ApplicantIncome    614 non-null    int64  
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         592 non-null    float64
 8   Loan_Amount_Term   600 non-null    float64
 9   Credit_History     564 non-null    float64
 10  Property_Area      614 non-null    object 
 11  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB


In [15]:
# Decision tree in Python can take only numerical / categorical colums. It cannot take string / obeject types. 
# The following code loops through each column and checks if the column type is object then converts those columns
# into categorical with each distinct value becoming a category or code.

for feature in df_train.columns: 
    if df_train[feature].dtype == 'object': 
        df_train[feature] = pd.Categorical(df_train[feature]).codes

In [16]:
df_train.fillna(df_train.median(), inplace=True)

In [17]:
df_train.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           1          0              0             5849   
1       1        1           2          0              0             4583   
2       1        1           1          0              1             3000   
3       1        1           1          1              0             2583   
4       1        0           1          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       128.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

   Property_Area  Loan_Status  
0              2            1  
1              0            0  
2              2            1  
3              2            1  
4              2            1

In [18]:
df_train.describe().T

count         mean          std    min      25%     50%  \
Gender             614.0     0.775244     0.465767   -1.0     1.00     1.0   
Married            614.0     0.643322     0.489511   -1.0     0.00     1.0   
Dependents         614.0     1.363192     0.935094   -1.0     1.00     1.0   
Education          614.0     0.218241     0.413389    0.0     0.00     0.0   
Self_Employed      614.0     0.081433     0.423472   -1.0     0.00     0.0   
ApplicantIncome    614.0  5403.459283  6109.041673  150.0  2877.50  3812.5   
CoapplicantIncome  614.0  1621.245798  2926.248369    0.0     0.00  1188.5   
LoanAmount         614.0   145.752443    84.107233    9.0   100.25   128.0   
Loan_Amount_Term   614.0   342.410423    64.428629   12.0   360.00   360.0   
Credit_History     614.0     0.855049     0.352339    0.0     1.00     1.0   
Property_Area      614.0     1.037459     0.787482    0.0     0.00     1.0   
Loan_Status        614.0     0.687296     0.463973    0.0     0.00     1.0   

                       75%      max  
Gender                1.00      1.0  
Married               1.00      1.0  
Dependents            2.00      3.0  
Education             0.00      1.0  
Self_Employed         0.00      1.0  
ApplicantIncome    5795.00  81000.0  
CoapplicantIncome  2297.25  41667.0  
LoanAmount          164.75    700.0  
Loan_Amount_Term    360.00    480.0  
Credit_History        1.00      1.0  
Property_Area         2.00      2.0  
Loan_Status           1.00      1.0

### check missing values

In [19]:
df_train.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [20]:
df_train[df_train < 0] = 0

In [21]:
df_train.describe().T

count         mean          std    min      25%     50%  \
Gender             614.0     0.796417     0.402991    0.0     1.00     1.0   
Married            614.0     0.648208     0.477919    0.0     0.00     1.0   
Dependents         614.0     1.387622     0.884658    0.0     1.00     1.0   
Education          614.0     0.218241     0.413389    0.0     0.00     0.0   
Self_Employed      614.0     0.133550     0.340446    0.0     0.00     0.0   
ApplicantIncome    614.0  5403.459283  6109.041673  150.0  2877.50  3812.5   
CoapplicantIncome  614.0  1621.245798  2926.248369    0.0     0.00  1188.5   
LoanAmount         614.0   145.752443    84.107233    9.0   100.25   128.0   
Loan_Amount_Term   614.0   342.410423    64.428629   12.0   360.00   360.0   
Credit_History     614.0     0.855049     0.352339    0.0     1.00     1.0   
Property_Area      614.0     1.037459     0.787482    0.0     0.00     1.0   
Loan_Status        614.0     0.687296     0.463973    0.0     0.00     1.0   

                       75%      max  
Gender                1.00      1.0  
Married               1.00      1.0  
Dependents            2.00      3.0  
Education             0.00      1.0  
Self_Employed         0.00      1.0  
ApplicantIncome    5795.00  81000.0  
CoapplicantIncome  2297.25  41667.0  
LoanAmount          164.75    700.0  
Loan_Amount_Term    360.00    480.0  
Credit_History        1.00      1.0  
Property_Area         2.00      2.0  
Loan_Status           1.00      1.0

### check duplicates

In [22]:
dups = df_train.duplicated()
dups.sum()

0

### Extracting the target column into separate vectors for training set 

In [23]:
X_train = df_train.drop(['Loan_Status'],axis = 1)

In [24]:
X_train.shape

(614, 11)

In [25]:
train_labels = df_train.pop('Loan_Status')

In [26]:
train_labels.shape

(614,)

### Decision Tree Classifier

In [27]:
dt_model = DecisionTreeClassifier(criterion = 'gini' )

In [28]:
dt_model.fit(X_train, train_labels)

DecisionTreeClassifier()

In [29]:
# importance of features in the tree building ( The importance of a feature is computed as the 
#(normalized) total reduction of the criterion brought by that feature. It is also known as the Gini importance )

print (pd.DataFrame(dt_model.feature_importances_, columns = ["Imp"], index = X_train.columns))

                        Imp
Gender             0.019305
Married            0.027329
Dependents         0.049846
Education          0.020242
Self_Employed      0.027625
ApplicantIncome    0.255701
CoapplicantIncome  0.083501
LoanAmount         0.155983
Loan_Amount_Term   0.037569
Credit_History     0.292201
Property_Area      0.030697


In [30]:
from sklearn import tree

train_char_label = ['No', 'Yes']
loan_prediction_Tree_File = open('G:\HACK Analytics vidhya\lon prediction\loan_prediction.dot','w')
dot_data = tree.export_graphviz(dt_model, out_file=loan_prediction_Tree_File, feature_names = list(X_train), class_names = list(train_char_label))

loan_prediction_Tree_File.close()

### Grid Search for finding out the optimal values for the hyper parameters

In [31]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [6, 7, 8],
    'min_samples_leaf': [18, 20, 23],
    'min_samples_split': [47, 50, 52,]
}

dt_model = DecisionTreeClassifier()

grid_search = GridSearchCV(estimator = dt_model, param_grid = param_grid, cv = 3)

In [32]:
grid_search.fit(X_train, train_labels)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [6, 7, 8],
                         'min_samples_leaf': [18, 20, 23],
                         'min_samples_split': [47, 50, 52]})

In [33]:
grid_search.best_params_

{'max_depth': 6, 'min_samples_leaf': 18, 'min_samples_split': 50}

In [34]:
best_grid = grid_search.best_estimator_

In [35]:
best_grid

DecisionTreeClassifier(max_depth=6, min_samples_leaf=18, min_samples_split=50)

### Regularising the Decision Tree

### Adding Tuning Parameters

In [36]:
reg_dt_model = DecisionTreeClassifier(criterion = 'gini', max_depth = 6,min_samples_leaf=20,min_samples_split=50)


In [37]:
reg_dt_model.fit(X_train, train_labels)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=20, min_samples_split=50)

### Generating New Tree

In [38]:
loan_prediction_tree_regularized = open('G:\HACK Analytics vidhya\lon prediction\loan_prediction_tree_regularized.dot','w')
dot_data = tree.export_graphviz(reg_dt_model, out_file= loan_prediction_tree_regularized , feature_names = list(X_train), class_names = list(train_char_label))

loan_prediction_tree_regularized.close()
dot_data

### Variable Importance

In [39]:
print (pd.DataFrame(reg_dt_model.feature_importances_, columns = ["Imp"], index = X_train.columns).sort_values('Imp',ascending=False))

                        Imp
Credit_History     0.787534
CoapplicantIncome  0.076697
Property_Area      0.047341
LoanAmount         0.045012
ApplicantIncome    0.024312
Married            0.019103
Gender             0.000000
Dependents         0.000000
Education          0.000000
Self_Employed      0.000000
Loan_Amount_Term   0.000000


### Predicting on Training dataset

In [40]:
ytrain_predict = reg_dt_model.predict(X_train)

In [41]:
print('ytrain_predict',ytrain_predict.shape)

ytrain_predict (614,)


In [42]:
from sklearn.metrics import classification_report,confusion_matrix

In [43]:
print(classification_report(train_labels, ytrain_predict))

              precision    recall  f1-score   support

           0       0.83      0.49      0.62       192
           1       0.81      0.95      0.87       422

    accuracy                           0.81       614
   macro avg       0.82      0.72      0.75       614
weighted avg       0.81      0.81      0.79       614



In [44]:
confusion_matrix(train_labels, ytrain_predict)

array([[ 95,  97],
       [ 19, 403]], dtype=int64)

In [45]:
reg_dt_model.score(X_train,train_labels)

0.8110749185667753

### Reading test data

In [46]:
df_test = pd.read_csv('test_lAUu6dG.csv')

In [47]:
df_test.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [48]:
X_test = df_test.drop(['Loan_ID'], axis = 1)

In [49]:
X_test.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male     Yes          0      Graduate            No             5720   
1   Male     Yes          1      Graduate            No             3076   
2   Male     Yes          2      Graduate            No             5000   
3   Male     Yes          2      Graduate            No             2340   
4   Male      No          0  Not Graduate            No             3276   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0       110.0             360.0             1.0   
1               1500       126.0             360.0             1.0   
2               1800       208.0             360.0             1.0   
3               2546       100.0             360.0             NaN   
4                  0        78.0             360.0             1.0   

  Property_Area  
0         Urban  
1         Urban  
2         Urban  
3         Urban  
4         Urban

In [50]:
X_test.shape

(367, 11)

In [51]:
X_test.describe().T

count         mean          std   min      25%     50%  \
ApplicantIncome    367.0  4805.599455  4910.685399   0.0  2864.00  3786.0   
CoapplicantIncome  367.0  1569.577657  2334.232099   0.0     0.00  1025.0   
LoanAmount         362.0   136.132597    61.366652  28.0   100.25   125.0   
Loan_Amount_Term   361.0   342.537396    65.156643   6.0   360.00   360.0   
Credit_History     338.0     0.825444     0.380150   0.0     1.00     1.0   

                      75%      max  
ApplicantIncome    5060.0  72529.0  
CoapplicantIncome  2430.5  24000.0  
LoanAmount          158.0    550.0  
Loan_Amount_Term    360.0    480.0  
Credit_History        1.0      1.0

In [52]:
X_test['Dependents'].replace('3+', 3, inplace=True)

In [53]:
X_test['Dependents'].value_counts()

0    200
2     59
1     58
3     40
Name: Dependents, dtype: int64

In [54]:
X_test.isnull().sum()

Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [55]:
# Decision tree in Python can take only numerical / categorical colums. It cannot take string / obeject types. 
# The following code loops through each column and checks if the column type is object then converts those columns
# into categorical with each distinct value becoming a category or code.

for feature in X_test.columns: 
    if X_test[feature].dtype == 'object': 
        X_test[feature] = pd.Categorical(X_test[feature]).codes

In [56]:
X_test.fillna(X_test.mean(), inplace=True)

In [57]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             367 non-null    int8   
 1   Married            367 non-null    int8   
 2   Dependents         367 non-null    int8   
 3   Education          367 non-null    int8   
 4   Self_Employed      367 non-null    int8   
 5   ApplicantIncome    367 non-null    int64  
 6   CoapplicantIncome  367 non-null    int64  
 7   LoanAmount         367 non-null    float64
 8   Loan_Amount_Term   367 non-null    float64
 9   Credit_History     367 non-null    float64
 10  Property_Area      367 non-null    int8   
dtypes: float64(3), int64(2), int8(6)
memory usage: 16.6 KB


In [58]:
X_test[X_test < 0] = 0

In [59]:
X_test.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [60]:
X_test.describe().T

count         mean          std   min     25%     50%  \
Gender             367.0     0.779292     0.415290   0.0     1.0     1.0   
Married            367.0     0.634877     0.482122   0.0     0.0     1.0   
Dependents         367.0     1.343324     0.906475   0.0     1.0     1.0   
Education          367.0     0.228883     0.420687   0.0     0.0     0.0   
Self_Employed      367.0     0.100817     0.301498   0.0     0.0     0.0   
ApplicantIncome    367.0  4805.599455  4910.685399   0.0  2864.0  3786.0   
CoapplicantIncome  367.0  1569.577657  2334.232099   0.0     0.0  1025.0   
LoanAmount         367.0   136.132597    60.946040  28.0   101.0   126.0   
Loan_Amount_Term   367.0   342.537396    64.620366   6.0   360.0   360.0   
Credit_History     367.0     0.825444     0.364778   0.0     1.0     1.0   
Property_Area      367.0     1.079019     0.824337   0.0     0.0     1.0   

                      75%      max  
Gender                1.0      1.0  
Married               1.0      1.0  
Dependents            2.0      3.0  
Education             0.0      1.0  
Self_Employed         0.0      1.0  
ApplicantIncome    5060.0  72529.0  
CoapplicantIncome  2430.5  24000.0  
LoanAmount          157.5    550.0  
Loan_Amount_Term    360.0    480.0  
Credit_History        1.0      1.0  
Property_Area         2.0      2.0

In [61]:
X_test.shape

(367, 11)

In [62]:
ytest_predict = reg_dt_model.predict(X_test)

In [63]:
print('ytest_predict',ytest_predict.shape)

ytest_predict (367,)


### Getting the Predicted Classes

In [64]:
ytest_predict

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

### Getting the Predicted Probabilities

In [65]:
ytest_predict_prob=reg_dt_model.predict_proba(X_test)

In [66]:
df_a = pd.DataFrame(ytest_predict)

In [67]:
df_test.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [68]:
df_b = df_test['Loan_ID']

In [69]:
df_b

0      LP001015
1      LP001022
2      LP001031
3      LP001035
4      LP001051
         ...   
362    LP002971
363    LP002975
364    LP002980
365    LP002986
366    LP002989
Name: Loan_ID, Length: 367, dtype: object

In [70]:
df_col_merged = pd.concat([df_b, df_a], axis=1)

In [71]:
df_merged= df_col_merged.rename(columns={0: 'Loan_Status'})

In [72]:
df_merged.head()

Loan_ID  Loan_Status
0  LP001015            1
1  LP001022            1
2  LP001031            1
3  LP001035            1
4  LP001051            1

In [73]:
df_merged['Loan_Status'].replace([1, 0], ['Y', 'N'], inplace = True)

In [74]:
df_merged.to_csv('merged_out.csv', index=False)

### Random Forest Classifier

In [75]:
from sklearn.ensemble import RandomForestClassifier

In [76]:
import warnings
warnings.filterwarnings('ignore')

In [77]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [4, 5, 6],
    'max_features': [6, 7, 8],
    'min_samples_leaf': [8, 9, 10],
    'min_samples_split': [30, 40, 50],
    'n_estimators': [101, 301]
}

rfcl = RandomForestClassifier()

grid_search = GridSearchCV(estimator = rfcl, param_grid = param_grid, cv = 3)

In [78]:
grid_search.fit(X_train, train_labels)

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [4, 5, 6], 'max_features': [6, 7, 8],
                         'min_samples_leaf': [8, 9, 10],
                         'min_samples_split': [30, 40, 50],
                         'n_estimators': [101, 301]})

In [79]:
best_grid = grid_search.best_estimator_

In [80]:
best_grid

RandomForestClassifier(max_depth=4, max_features=6, min_samples_leaf=8,
                       min_samples_split=30, n_estimators=101)

In [81]:
ytrain_predict = best_grid.predict(X_train)


In [82]:
print(classification_report(train_labels,ytrain_predict))

              precision    recall  f1-score   support

           0       0.92      0.43      0.58       192
           1       0.79      0.98      0.88       422

    accuracy                           0.81       614
   macro avg       0.86      0.71      0.73       614
weighted avg       0.83      0.81      0.78       614



In [148]:
confusion_matrix(train_labels, ytrain_predict)

array([[ 85, 107],
       [  7, 415]], dtype=int64)

In [83]:
ytest_predict = best_grid.predict(X_test)

In [84]:
ytest_predict

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

### MLP Classifier (Artificial Neural Network)

In [85]:
from sklearn.neural_network import MLPClassifier

In [86]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_trains = sc.fit_transform(X_train)

In [149]:
param_grid = {
    'hidden_layer_sizes': [(500)],
    'activation': ['logistic', 'relu'],
    'solver': ['sgd', 'adam'],
    'tol': [0.1,0.01],
    'max_iter' : [10000]
}

MLP= MLPClassifier()

grid_search = GridSearchCV(estimator = MLP, param_grid = param_grid, cv = 3)

In [150]:
grid_search.fit(X_trains, train_labels)

GridSearchCV(cv=3, estimator=MLPClassifier(),
             param_grid={'activation': ['logistic', 'relu'],
                         'hidden_layer_sizes': [500], 'max_iter': [10000],
                         'solver': ['sgd', 'adam'], 'tol': [0.1, 0.01]})

In [151]:
grid_search.best_params_

{'activation': 'relu',
 'hidden_layer_sizes': 500,
 'max_iter': 10000,
 'solver': 'adam',
 'tol': 0.1}

In [152]:
best_grid2 = grid_search.best_estimator_

In [153]:
ytrain_predict = best_grid2.predict(X_trains)

In [154]:
print(classification_report(train_labels,ytrain_predict))

              precision    recall  f1-score   support

           0       0.92      0.44      0.59       192
           1       0.79      0.98      0.88       422

    accuracy                           0.81       614
   macro avg       0.86      0.71      0.74       614
weighted avg       0.83      0.81      0.79       614



In [155]:
ytest_predict = best_grid.predict(X_test)

In [156]:
ytest_predict

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

In [157]:
confusion_matrix(train_labels, ytrain_predict)

array([[ 84, 108],
       [  7, 415]], dtype=int64)

In [158]:
df_a = pd.DataFrame(ytest_predict)

In [159]:
df_col_merged = pd.concat([df_b, df_a], axis=1)

In [160]:
df_merged= df_col_merged.rename(columns={0: 'Loan_Status'})

In [161]:
df_merged.head()

Loan_ID  Loan_Status
0  LP001015            1
1  LP001022            1
2  LP001031            1
3  LP001035            1
4  LP001051            1

In [162]:
df_merged['Loan_Status'].replace([1, 0], ['Y', 'N'], inplace = True)

In [163]:
df_merged.to_csv('mlp_out.csv', index=False)